version: '3'
services:
  init:
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        chown -R 1000:1000 /data
        echo "done grany data directory permission"
    volumes:
      - /mnt/blockstore/arbitrum:/data
  arbitrum:
    image: offchainlabs/nitro-node:v2.0.11-8e786ec
    container_name: arbitrum
    restart: always
    ports:
      - "8557:8547"
      - "8558:8548"
      - "8555:8545"
    volumes:
      - /mnt/blockstore/arbitrum:/home/user/.arbitrum
    command: >
      --l1.url=https://rpc.ankr.com/eth/<api>
      --l2.chain-id=42161
      --http.api=net,web3,eth,debug
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.vhosts=*
      --ws.addr=0.0.0.0
      --ws.origins=*
      --ws.port=8548
      --node.rpc.gas-cap=0
      --node.rpc.tx-fee-cap=0
      --node.rpc.evm-timeout=60s
      --init.empty
      --ipc.path=/home/user/.arbitrum/
