version: '3'
services:
  init:
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        chown -R 1000:1000 /data
        echo "done grany data directory permission"
    volumes:
      - /mnt/blockstore/arbitrum:/data
  arbitrum:
    image: offchainlabs/nitro-node:v2.0.11-8e786ec
    container_name: arbitrum
    restart: always
    ports:
      - "8557:8547"
      - "8558:8548"
    volumes:
      - /mnt/blockstore/arbitrum:/home/user/.arbitrum
    command: >
      --l1.url https://mainnet.infura.io/v3/asxas
      --l2.chain-id=42161
      --http.api=net,web3,eth,debug
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.vhosts=*
      --ws.port=8545
      --init.import-file=/home/user/.arbitrum/nitro.tar
